export const MODE = {SLAVE:"SLAVE", MASTER:"MASTER", GUI:"GUI", STROLLER:"STROLLER" };
export const EVENT = {SENSOR_DATA:"SENSOR_DATA", BRAKE_DATA:"BRAKE_DATA", TEMP_DATA:"TEMP_DATA", FRONT_DATA:"FRONT_ASSIST_ACTIVATED"};
export const SYSTEM_SET = {FRONT_ALERT:"FRONT_ASSIST_ENABLED", REMOTE:"REMOTE_ENABLED"};
export const ROLES = {MASTER:"MASTER", SLAVE:"SLAVE", RPI:"RPI", GUI:"GUI"};


